<a href="https://colab.research.google.com/github/harigovindankjhari-afk/AI-DATASCIENCE_ASSIGNMENTS/blob/main/Appriori_and_Association_rules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
from mlxtend.frequent_patterns import apriori,association_rules
import warnings
warnings.filterwarnings('ignore')

In [61]:
import pandas as pd

In [62]:
df=pd.DataFrame([
    ['Milk','Bread','Butter'],
    ['Beer','Bread',None],
    ['Milk','Bread','Beer'],
    ['Bread','Butter',None],
    ['Milk','Butter',None]
    ])
df

       0       1       2
0   Milk   Bread  Butter
1   Beer   Bread    None
2   Milk   Bread    Beer
3  Bread  Butter    None
4   Milk  Butter    None

In [63]:
df=pd.get_dummies(df.stack()).groupby(level=0).sum()

In [64]:
df

   Beer  Bread  Butter  Milk
0     0      1       1     1
1     1      1       0     0
2     1      1       0     1
3     0      1       1     0
4     0      0       1     1

In [85]:
frequent = apriori(df, min_support=0.1, use_colnames=True)
rules = association_rules(frequent, metric='confidence', min_threshold=0.22)

In [86]:
frequent

    support               itemsets
0       0.4                 (Beer)
1       0.8                (Bread)
2       0.6               (Butter)
3       0.6                 (Milk)
4       0.4          (Bread, Beer)
5       0.2           (Beer, Milk)
6       0.4        (Butter, Bread)
7       0.4          (Bread, Milk)
8       0.4         (Butter, Milk)
9       0.2    (Bread, Beer, Milk)
10      0.2  (Butter, Bread, Milk)

In [87]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Bread),(Beer),0.8,0.4,0.4,0.500000,1.250000,1.0,0.08,1.200000,1.000000,0.500000,0.166667,0.750000
1,(Beer),(Bread),0.4,0.8,0.4,1.000000,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000000,0.750000
2,(Beer),(Milk),0.4,0.6,0.2,0.500000,0.833333,1.0,-0.04,0.800000,-0.250000,0.250000,-0.250000,0.416667
3,(Milk),(Beer),0.6,0.4,0.2,0.333333,0.833333,1.0,-0.04,0.900000,-0.333333,0.250000,-0.111111,0.416667
4,(Butter),(Bread),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.600000,-0.333333,0.400000,-0.666667,0.583333
5,(Bread),(Butter),0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.800000,-0.500000,0.400000,-0.250000,0.583333
6,(Bread),(Milk),0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.800000,-0.500000,0.400000,-0.250000,0.583333
7,(Milk),(Bread),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.600000,-0.333333,0.400000,-0.666667,0.583333
8,(Butter),(Milk),0.6,0.6,0.4,0.666667,1.111111,1.0,0.04,1.200000,0.250000,0.500000,0.166667,0.666667
9,(Milk),(Butter),0.6,0.6,0.4,0.666667,1.111111,1.0,0.04,1.200000,0.250000,0.500000,0.166667,0.666667
10,"(Bread, Beer)",(Milk),0.4,0.6,0.2,0.500000,0.833333,1.0,-0.04,0.800000,-0.250000,0.250000,-0.250000,0.416667
11,"(Bread, Milk)",(Beer),0.4,0.4,0.2,0.500000,1.250000,1.0,0.04,1.200000,0.333333,0.333333,0.166667,0.500000
12,"(Beer, Milk)",(Bread),0.2,0.8,0.2,1.000000,1.250000,1.0,0.04,inf,0.250000,0.250000,1.000000,0.625000
13,(Bread),"(Beer, Milk)",0.8,0.2,0.2,0.250000,1.250000,1.0,0.04,1.066667,1.000000,0.250000,0.062500,0.625000
14,(Beer),"(Bread, Milk)",0.4,0.4,0.2,0.500000,1.250000,1.0,0.04,1.200000,0.333333,0.333333,0.166667,0.500000
15,(Milk),"(Bread, Beer)",0.6,0.4,0.2,0.333333,0.833333,1.0,-0.04,0.900000,-0.333333,0.250000,-0.111111,0.416667
16,"(Butter, Bread)",(Milk),0.4,0.6,0.2,0.500000,0.833333,1.0,-0.04,0.800000,-0.250000,0.250000,-0.250000,0.416667
17,"(Butter, Milk)",(Bread),0.4,0.8,0.2,0.500000,0.625000,1.0,-0.12,0.400000,-0.500000,0.200000,-1.500000,0.375000
18,"(Bread, Milk)",(Butter),0.4,0.6,0.2,0.500000,0.833333,1.0,-0.04,0.800000,-0.250000,0.250000,-0.250000,0.416667
19,(Butter),"(Bread, Milk)",0.6,0.4,0.2,0.333333,0.833333,1.0,-0.04,0.900000,-0.333333,0.250000,-0.111111,0.416667
20,(Bread),"(Butter, Milk)",0.8,0.4,0.2,0.250000,0.625000,1.0,-0.12,0.800000,-0.750000,0.200000,-0.250000,0.375000
21,(Milk),"(Butter, Bread)",0.6,0.4,0.2,0.333333,0.833333,1.0,-0.04,0.900000,-0.333333,0.250000,-0.111111,0.416667

In [88]:
#Lift value above 1, +ve relation
#Lift value below 1, -ve relation
#Lift value = 1 , no relation