<a href="https://colab.research.google.com/github/harigovindankjhari-afk/AI-DATASCIENCE_ASSIGNMENTS/blob/main/Appriori_and_Association_rules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
from mlxtend.frequent_patterns import apriori,association_rules
import warnings
warnings.filterwarnings('ignore')

In [61]:
import pandas as pd

In [62]:
df=pd.DataFrame([
    ['Milk','Bread','Butter'],
    ['Beer','Bread',None],
    ['Milk','Bread','Beer'],
    ['Bread','Butter',None],
    ['Milk','Butter',None]
    ])
df

       0       1       2
0   Milk   Bread  Butter
1   Beer   Bread    None
2   Milk   Bread    Beer
3  Bread  Butter    None
4   Milk  Butter    None

In [63]:
df=pd.get_dummies(df.stack()).groupby(level=0).sum()

In [64]:
df

   Beer  Bread  Butter  Milk
0     0      1       1     1
1     1      1       0     0
2     1      1       0     1
3     0      1       1     0
4     0      0       1     1

In [65]:
frequent = apriori(df, min_support=0.1, use_colnames=True)
rules = association_rules(frequent, metric='confidence', min_threshold=0.7)

In [66]:
frequent

    support               itemsets
0       0.4                 (Beer)
1       0.8                (Bread)
2       0.6               (Butter)
3       0.6                 (Milk)
4       0.4          (Bread, Beer)
5       0.2           (Beer, Milk)
6       0.4        (Butter, Bread)
7       0.4          (Bread, Milk)
8       0.4         (Butter, Milk)
9       0.2    (Bread, Beer, Milk)
10      0.2  (Butter, Bread, Milk)

In [67]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Beer),(Bread),0.4,0.8,0.4,1.0,1.25,1.0,0.08,inf,0.333333,0.50,1.0,0.750
1,"(Beer, Milk)",(Bread),0.2,0.8,0.2,1.0,1.25,1.0,0.04,inf,0.250000,0.25,1.0,0.625