<a href="https://colab.research.google.com/github/harigovindankjhari-afk/AI-DATASCIENCE_ASSIGNMENTS/blob/main/overfitting_and_underfitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Zomato Restaurant Dataset.csv to Zomato Restaurant Dataset.csv

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression,Lasso,Ridge

In [ ]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)

In [ ]:
data = pd.read_csv('Zomato Restaurant Dataset.csv')
data

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [ ]:
data.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [ ]:
data.nunique()

Restaurant ID           9551
Restaurant Name         7446
Country Code              15
City                     141
Address                 8918
Locality                1208
Locality Verbose        1265
Longitude               8120
Latitude                8677
Cuisines                1825
Average Cost for two     140
Currency                  12
Has Table booking          2
Has Online delivery        2
Is delivering now          2
Switch to order menu       1
Price range                4
Aggregate rating          33
Rating color               6
Rating text                6
Votes                   1012
dtype: int64

In [ ]:
data.isna().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [ ]:
data.isna().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [ ]:
data.dtypes

Restaurant ID             int64
Restaurant Name          object
Country Code              int64
City                     object
Address                  object
Locality                 object
Locality Verbose         object
Longitude               float64
Latitude                float64
Cuisines                 object
Average Cost for two      int64
Currency                 object
Has Table booking        object
Has Online delivery      object
Is delivering now        object
Switch to order menu     object
Price range               int64
Aggregate rating        float64
Rating color             object
Rating text              object
Votes                     int64
dtype: object

In [ ]:
X= data.drop('Aggregate rating',axis=1)
Y=data['Aggregate rating']
X

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,No,No,3,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,1200,Botswana Pula(P),Yes,No,No,No,3,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,No,No,4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),No,No,No,No,4,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,No,No,4,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,80,Turkish Lira(TL),No,No,No,No,3,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",105,Turkish Lira(TL),No,No,No,No,3,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",170,Turkish Lira(TL),No,No,No,No,4,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,120,Turkish Lira(TL),No,No,No,No,4,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,55,Turkish Lira(TL),No,No,No,No,2,Green,Very Good,591

In [ ]:
Y
lr=LinearRegression()

In [ ]:
import pandas as pd
# Temporarily set pandas display options to show all rows
with pd.option_context('display.max_rows', None):
    display(Y)

0       4.8
1       4.5
2       4.4
3       4.9
4       4.8
5       4.4
6       4.0
7       4.2
8       4.9
9       4.8
10      4.9
11      4.2
12      4.8
13      4.2
14      4.3
15      3.6
16      4.0
17      4.5
18      4.5
19      4.4
20      4.7
21      4.5
22      3.0
23      3.8
24      3.7
25      3.8
26      3.2
27      3.1
28      3.7
29      3.7
30      0.0
31      4.1
32      3.1
33      3.6
34      4.3
35      4.2
36      3.6
37      4.0
38      3.2
39      4.9
40      3.3
41      3.6
42      4.0
43      4.8
44      4.7
45      4.5
46      4.2
47      4.8
48      4.9
49      4.6
50      4.9
51      4.6
52      4.3
53      4.0
54      4.6
55      4.4
56      4.2
57      4.2
58      0.0
59      4.7
60      4.6
61      4.3
62      4.5
63      4.4
64      3.1
65      4.1
66      4.8
67      4.6
68      3.9
69      0.0
70      3.4
71      3.5
72      4.3
73      3.9
74      4.3
75      4.3
76      4.4
77      0.0
78      0.0
79      4.4
80      4.6
81      4.1
82      3.3
83      3.3
84      3.4
85      3.4
86      3.4
87      3.4
88      3.5
89      3.9
90      3.7
91      3.5
92      3.6
93      3.8
94      3.9
95      3.5
96      3.5
97      3.6
98      3.5
99      3.8
100     3.7
101     3.4
102     3.5
103     4.5
104     4.5
105     4.6
106     3.9
107     3.7
108     4.3
109     4.2
110     4.0
111     4.1
112     4.3
113     4.2
114     4.1
115     4.1
116     4.2
117     4.1
118     4.1
119     4.4
120     4.4
121     4.2
122     4.1
123     4.6
124     4.9
125     4.5
126     3.9
127     3.9
128     3.8
129     3.5
130     4.3
131     4.1
132     4.4
133     4.0
134     4.0
135     4.2
136     4.0
137     4.0
138     3.9
139     4.1
140     4.0
141     4.3
142     4.2
143     3.2
144     4.6
145     4.5
146     4.6
147     4.5
148     3.9
149     4.3
150     4.1
151     4.2
152     4.3
153     4.4
154     4.1
155     4.4
156     4.3
157     4.4
158     4.4
159     4.0
160     4.1
161     4.3
162     4.0
163     4.0
164     4.4
165     3.7
166     4.1
167     4.1
168     4.1
169     4.4
170     4.2
171     4.2
172     4.2
173     3.8
174     4.1
175     4.9
176     4.5
177     3.6
178     3.8
179     4.3
180     4.3
181     4.1
182     4.0
183     4.2
184     4.7
185     3.7
186     4.3
187     3.1
188     3.3
189     4.6
190     4.5
191     3.8
192     3.9
193     3.9
194     3.7
195     3.6
196     3.7
197     4.2
198     4.3
199     4.0
200     4.0
201     4.0
202     4.1
203     4.1
204     4.2
205     4.3
206     4.0
207     4.4
208     3.0
209     3.7
210     4.4
211     4.4
212     3.9
213     4.9
214     3.8
215     3.8
216     3.8
217     3.7
218     4.1
219     4.1
220     4.1
221     4.6
222     4.3
223     4.2
224     3.7
225     4.1
226     4.3
227     4.2
228     4.1
229     4.6
230     4.5
231     3.9
232     4.0
233     4.1
234     3.4
235     4.9
236     3.9
237     3.7
238     0.0
239     0.0
240     4.3
241     4.0
242     4.1
243     4.3
244     4.0
245     4.1
246     4.1
247     4.2
248     4.2
249     4.5
250     4.9
251     4.5
252     4.1
253     4.0
254     3.2
255     4.5
256     4.6
257     4.4
258     4.2
259     4.3
260     4.8
261     4.2
262     4.1
263     4.1
264     4.0
265     4.3
266     3.8
267     4.0
268     4.2
269     3.6
270     3.4
271     3.3
272     3.4
273     3.3
274     3.4
275     3.5
276     3.6
277     3.5
278     3.6
279     3.7
280     3.6
281     3.8
282     3.5
283     3.5
284     3.6
285     3.6
286     3.6
287     3.5
288     3.7
289     3.6
290     4.1
291     3.7
292     3.5
293     3.7
294     4.4
295     4.1
296     3.8
297     3.9
298     3.9
299     4.4
300     4.1
301     3.8
302     4.3
303     4.1
304     4.9
305     4.6
306     3.8
307     4.2
308     4.3
309     4.2
310     3.8
311     3.9
312     2.2
313     4.0
314     3.8
315     3.8
316     4.1
317     3.7
318     3.8
319     3.6
320     4.5
321     3.6
322     3.5
323     3.9
324     4.9
325     4.6
326     4.5
327     4.5
328     3.8
329     4.1
330     4.0
331     4.3
332     4.2
333     4.2
334     3.7
335     3.7
336     3.7
337     3.8
338     4.1
339     4.0
340     4.2
341     4.0
342     4.1
343     2.9
344     2.4
345     3.8
346     3.4
347     3.6
348     2.4
349     3.6
350     4.4
351     4.5
352     4.7
353     4.3
354     4.6
355     4.6
356     4.3
357     4.4
358     4.6
359     4.4
360     4.4
361     4.8
362     4.9
363     4.9
364     4.7
365     3.6
366     4.2
367     4.4
368     4.4
369     4.4
370     4.4
371     2.6
372     3.4
373     4.2
374     4.9
375     4.6
376     4.5
377     3.7
378     3.9
379     3.7
380     4.2
381     4.1
382     4.4
383     4.3
384     4.0
385     4.1
386     3.9
387     3.5
388     4.2
389     4.4
390     4.3
391     4.7
392     4.4
393     3.7
394     3.7
395     3.5
396     3.6
397     3.6
398     3.7
399     3.6
400     3.5
401     3.8
402     3.8
403     3.7
404     3.5
405     3.7
406     3.6
407     3.6
408     3.6
409     3.8
410     3.7
411     3.6
412     0.0
413     4.1
414     3.3
415     4.0
416     4.5
417     4.7
418     4.7
419     4.5
420     4.5
421     4.2
422     4.2
423     4.6
424     4.2
425     4.4
426     4.3
427     4.3
428     4.9
429     4.9
430     4.6
431     3.9
432     4.4
433     4.0
434     4.2
435     4.2
436     3.3
437     4.7
438     4.6
439     4.5
440     4.5
441     3.7
442     3.8
443     4.1
444     4.4
445     4.2
446     4.1
447     4.1
448     4.3
449     4.3
450     4.0
451     4.3
452     4.4
453     4.1
454     3.8
455     3.9
456     3.4
457     4.0
458     3.8
459     3.1
460     3.8
461     3.9
462     4.2
463     4.1
464     3.2
465     3.2
466     3.7
467     3.0
468     3.8
469     3.9
470     3.1
471     3.2
472     3.2
473     3.8
474     3.9
475     3.2
476     3.7
477     3.6
478     3.8
479     3.6
480     3.7
481     3.6
482     3.8
483     3.8
484     3.7
485     3.9
486     3.7
487     3.8
488     3.7
489     3.7
490     3.8
491     3.9
492     4.0
493     4.0
494     4.0
495     3.5
496     4.6
497     4.6
498     4.1
499     4.1
500     4.1
501     4.7
502     3.9
503     3.9
504     4.4
505     4.4
506     4.2
507     4.9
508     4.5
509     4.9
510     4.5
511     4.7
512     4.8
513     4.5
514     4.0
515     4.4
516     4.4
517     4.1
518     3.4
519     3.1
520     3.9
521     3.7
522     3.8
523     3.7
524     3.8
525     3.7
526     3.7
527     3.7
528     3.9
529     3.8
530     3.5
531     3.9
532     3.7
533     3.5
534     3.8
535     3.8
536     3.8
537     4.1
538     4.3
539     3.6
540     4.3
541     3.2
542     3.7
543     3.9
544     3.8
545     3.7
546     3.6
547     3.6
548     3.6
549     3.8
550     3.7
551     3.6
552     3.6
553     3.6
554     3.6
555     3.6
556     3.7
557     3.6
558     3.7
559     3.5
560     3.9
561     3.9
562     3.2
563     3.3
564     4.6
565     4.6
566     4.4
567     4.3
568     4.2
569     4.6
570     4.1
571     4.4
572     4.0
573     3.6
574     4.5
575     4.0
576     4.0
577     4.0
578     4.3
579     4.0
580     4.9
581     4.7
582     4.2
583     4.6
584     3.9
585     4.1
586     4.3
587     4.5
588     4.5
589     4.9
590     4.9
591     4.8
592     4.5
593     4.5
594     4.3
595     4.3
596     4.4
597     4.9
598     4.4
599     3.2
600     4.7
601     4.3
602     3.7
603     4.3
604     3.9
605     3.8
606     4.1
607     4.3
608     3.9
609     4.1
610     4.1
611     4.2
612     4.1
613     2.4
614     4.2
615     4.2
616     4.2
617     3.8
618     3.9
619     4.8
620     4.1
621     4.5
622     3.8
623     4.2
624     3.9
625     3.5
626     3.6
627     4.0
628     4.2
629     4.0
630     4.3
631     4.0
632     3.6
633     3.8
634     3.9
635     4.1
636     3.4
637     4.9
638     3.8
639     3.9
640     3.7
641     4.4
642     4.2
643     4.1
644     4.2
645     3.7
646     4.5
647     4.1
648     4.3
649     4.4
650     4.4
651     3.8
652     3.6
653     4.6
654     4.4
655     4.3
656     3.8
657     4.3
658     4.0
659     4.4
660     4.5
661     4.1
662     4.1
663     3.9
664     4.0
665     3.4
666     3.3
667     3.2
668     3.4
669     3.4
670     3.4
671     3.4
672     3.3
673     3.2
674     3.4
675     3.4
676     3.2
677     3.3
678     3.4
679     3.6
680     3.7
681     3.5
682     3.6
683     3.5
684     3.3
685     3.4
686     3.9
687     4.0
688     3.4
689     3.6
690     3.5
691     3.4
692     3.4
693     3.5
694     3.6
695     3.9
696     3.4
697     3.7
698     3.5
699     3.8
700     3.8
701     4.1
702     4.1
703     3.8
704     3.5
705     4.1
706     3.6
707     3.3
708     3.3
709     3.1
710     3.4
711     3.4
712     3.4
713     3.3
714     3.4
715     3.6
716     3.5
717     3.3
718     3.3
719     3.4
720     3.7
721     3.2
722     3.4
723     3.3
724     3.3
725     3.3
726     4.1
727     4.7
728     4.8
729     3.9
730     4.2
731     4.0
732     4.3
733     4.6
734     4.7
735     4.7
736     4.1
737     4.3
738     4.5
739     4.6
740     4.4
741     4.6
742     4.2
743     4.5
744     3.9
745     4.4
746     3.3
747     3.4
748     4.9
749     3.9
750     4.2
751     4.0
752     4.0
753     4.1
754     3.8
755     3.8
756     3.5
757     3.6
758     3.6
759     4.1
760     4.4
761     4.1
762     4.3
763     3.9
764     3.8
765     4.3
766     3.9
767     4.1
768     4.6
769     4.5
770     3.9
771     4.0
772     3.7
773     4.1
774     3.6
775     3.8
776     3.7
777     3.7
778     3.8
779     4.0
780     4.0
781     4.3
782     4.1
783     3.8
784     4.2
785     4.3
786     3.5
787     3.7
788     4.2
789     4.3
790     4.1
791     4.0
792     4.0
793     4.5
794     4.3
795     3.8
796     3.4
797     4.1
798     4.1
799     4.0
800     4.2
801     3.3
802     4.4
803     4.5
804     4.0
805     4.2
806     3.8
807     4.4
808     4.2
809     4.8
810     4.2
811     4.6
812     4.1
813     4.0
814     4.6
815     4.2
816     3.8
817     4.3
818     4.4
819     4.3
820     4.5
821     4.4
822     4.9
823     4.6
824     4.0
825     4.6
826     3.9
827     3.8
828     3.5
829     4.3
830     4.1
831     3.8
832     4.5
833     3.8
834     3.9
835     4.2
836     4.0
837     4.0
838     4.0
839     4.3
840     4.2
841     4.9
842     4.2
843     4.3
844     4.4
845     3.6
846     3.8
847     3.9
848     3.9
849     4.2
850     4.9
851     4.3
852     4.0
853     3.8
854     4.0
855     4.1
856     3.9
857     3.9
858     3.9
859     3.9
860     4.4
861     4.0
862     4.1
863     4.2
864     4.2
865     2.9
866     2.8
867     2.8
868     2.9
869     2.8
870     3.0
871     0.0
872     0.0
873     0.0
874     0.0
875     2.9
876     3.0
877     2.9
878     0.0
879     0.0
880     0.0
881     2.8
882     3.4
883     3.4
884     3.8
885     3.6
886     3.6
887     0.0
888     0.0
889     0.0
890     2.1
891     4.0
892     4.1
893     3.2
894     2.7
895     3.4
896     2.4
897     0.0
898     2.8
899     0.0
900     0.0
901     0.0
902     0.0
903     0.0
904     0.0
905     0.0
906     0.0
907     0.0
908     0.0
909     3.0
910     3.2
911     2.8
912     0.0
913     2.8
914     3.1
915     3.0
916     3.1
917     2.9
918     0.0
919     0.0
920     0.0
921     3.3
922     3.0
923     2.6
924     2.9
925     2.9
926     3.1
927     0.0
928     0.0
929     0.0
930     3.2
931     3.4
932     3.3
933     2.7
934     3.4
935     3.3
936     2.6
937     3.3
938     3.4
939     2.7
940     2.6
941     2.7
942     3.4
943     4.5
944     3.6
945     3.5
946     3.8
947     3.5
948     3.6
949     3.7
950     3.6
951     3.5
952     3.6
953     3.5
954     3.6
955     3.8
956     3.5
957     3.6
958     3.8
959     3.5
960     4.1
961     2.9
962     2.9
963     2.5
964     3.1
965     3.0
966     3.4
967     3.3
968     3.1
969     3.1
970     0.0
971     0.0
972     0.0
973     0.0
974     0.0
975     0.0
976     0.0
977     0.0
978     2.8
979     2.7
980     2.7
981     2.7
982     2.8
983     2.7
984     3.2
985     3.4
986     3.3
987     0.0
988     3.0
989     3.3
990     2.8
991     3.1
992     2.8
993     3.0
994     0.0
995     0.0
996     0.0
997     0.0
998     0.0
999     0.0
1000    0.0
1001    0.0
1002    0.0
1003    0.0
1004    2.6
1005    2.9
1006    0.0
1007    0.0
1008    3.1
1009    0.0
1010    0.0
1011    3.1
1012    3.1
1013    2.9
1014    0.0
1015    0.0
1016    0.0
1017    0.0
1018    0.0
1019    0.0
1020    2.7
1021    2.7
1022    0.0
1023    0.0
1024    0.0
1025    0.0
1026    3.0
1027    3.3
1028    3.1
1029    3.1
1030    2.8
1031    2.7
1032    3.1
1033    2.9
1034    2.7
1035    3.6
1036    0.0
1037    0.0
1038    0.0
1039    0.0
1040    0.0
1041    0.0
1042    0.0
1043    0.0
1044    0.0
1045    0.0
1046    3.0
1047    0.0
1048    0.0
1049    0.0
1050    0.0
1051    0.0
1052    2.9
1053    3.1
1054    2.9
1055    2.9
1056    0.0
1057    0.0
1058    0.0
1059    0.0
1060    0.0
1061    0.0
1062    0.0
1063    3.2
1064    2.5
1065    3.5
1066    0.0
1067    0.0
1068    2.7
1069    3.0
1070    3.0
1071    2.9
1072    3.0
1073    3.1
1074    2.9
1075    3.0
1076    0.0
1077    3.0
1078    2.9
1079    3.2
1080    3.4
1081    2.9
1082    3.0
1083    3.2
1084    3.1
1085    3.3
1086    3.4
1087    3.5
1088    3.1
1089    0.0
1090    0.0
1091    0.0
1092    0.0
1093    0.0
1094    2.9
1095    3.0
1096    2.8
1097    2.8
1098    2.6
1099    3.0
1100    3.1
1101    3.1
1102    3.0
1103    3.0
1104    0.0
1105    0.0
1106    0.0
1107    0.0
1108    0.0
1109    0.0
1110    0.0
1111    0.0
1112    0.0
1113    3.0
1114    3.1
1115    3.3
1116    2.8
1117    3.0
1118    3.6
1119    3.9
1120    0.0
1121    0.0
1122    2.5
1123    3.4
1124    3.3
1125    3.4
1126    3.2
1127    2.9
1128    2.6
1129    3.3
1130    3.2
1131    3.0
1132    2.7
1133    2.6
1134    3.3
1135    3.1
1136    3.6
1137    3.6
1138    1.8
1139    3.3
1140    3.2
1141    4.5
1142    4.8
1143    4.4
1144    3.5
1145    4.6
1146    3.8
1147    4.3
1148    4.2
1149    4.4
1150    3.7
1151    4.3
1152    3.8
1153    4.2
1154    4.6
1155    3.7
1156    4.5
1157    4.7
1158    4.3
1159    4.4
1160    4.2
1161    3.4
1162    2.7
1163    4.3
1164    4.0
1165    3.0
1166    3.0
1167    3.0
1168    0.0
1169    3.0
1170    3.1
1171    2.9
1172    0.0
1173    0.0
1174    0.0
1175    0.0
1176    0.0
1177    0.0
1178    0.0
1179    0.0
1180    0.0
1181    0.0
1182    0.0
1183    0.0
1184    0.0
1185    0.0
1186    0.0
1187    0.0
1188    2.8
1189    2.9
1190    3.9
1191    3.4
1192    3.4
1193    3.4
1194    3.3
1195    3.4
1196    2.5
1197    3.8
1198    3.9
1199    3.6
1200    4.3
1201    3.8
1202    3.0
1203    3.5
1204    3.5
1205    3.4
1206    3.2
1207    0.0
1208    3.9
1209    3.7
1210    3.7
1211    3.5
1212    4.0
1213    4.2
1214    4.2
1215    4.1
1216    3.9
1217    3.7
1218    2.8
1219    3.3
1220    4.6
1221    4.6
1222    4.5
1223    3.7
1224    3.7
1225    3.7
1226    3.7
1227    3.6
1228    3.9
1229    3.8
1230    3.6
1231    3.6
1232    3.9
1233    3.6
1234    3.8
1235    3.9
1236    3.9
1237    3.8
1238    3.6
1239    3.5
1240    3.9
1241    3.9
1242    3.8
1243    3.8
1244    3.7
1245    3.8
1246    3.9
1247    2.4
1248    4.0
1249    4.3
1250    4.0
1251    4.0
1252    4.3
1253    4.1
1254    4.0
1255    4.0
1256    4.0
1257    4.1
1258    4.0
1259    4.0
1260    3.1
1261    3.8
1262    3.8
1263    2.4
1264    4.2
1265    3.4
1266    3.3
1267    2.5
1268    3.8
1269    3.7
1270    3.8
1271    3.8
1272    3.9
1273    3.6
1274    3.8
1275    3.5
1276    3.5
1277    3.5
1278    2.4
1279    4.3
1280    4.0
1281    4.1
1282    3.2
1283    2.6
1284    2.8
1285    3.0
1286    2.6
1287    3.3
1288    2.8
1289    3.3
1290    3.3
1291    3.1
1292    2.5
1293    3.9
1294    3.5
1295    0.0
1296    2.2
1297    3.4
1298    3.1
1299    3.2
1300    2.9
1301    3.0
1302    2.9
1303    3.4
1304    3.2
1305    3.2
1306    3.1
1307    2.9
1308    2.9
1309    2.8
1310    3.1
1311    3.1
1312    4.6
1313    3.9
1314    3.8
1315    3.9
1316    3.8
1317    3.5
1318    3.6
1319    3.8
1320    0.0
1321    0.0
1322    0.0
1323    0.0
1324    3.8
1325    0.0
1326    0.0
1327    0.0
1328    0.0
1329    0.0
1330    0.0
1331    0.0
1332    0.0
1333    0.0
1334    2.5
1335    3.2
1336    3.0
1337    2.6
1338    3.2
1339    3.3
1340    3.1
1341    3.2
1342    3.2
1343    3.3
1344    2.8
1345    2.9
1346    3.0
1347    3.4
1348    3.0
1349    3.2
1350    3.4
1351    3.4
1352    2.7
1353    3.3
1354    3.4
1355    3.1
1356    2.5
1357    2.5
1358    3.4
1359    2.6
1360    3.1
1361    3.1
1362    3.1
1363    2.7
1364    3.4
1365    3.2
1366    3.0
1367    3.2
1368    3.1
1369    3.2
1370    3.4
1371    3.2
1372    2.7
1373    2.9
1374    3.3
1375    3.0
1376    3.2
1377    3.2
1378    2.7
1379    3.3
1380    2.8
1381    4.9
1382    3.7
1383    3.6
1384    3.5
1385    3.9
1386    3.7
1387    3.6
1388    3.5
1389    3.5
1390    3.5
1391    3.6
1392    3.8
1393    3.5
1394    3.5
1395    2.0
1396    2.1
1397    2.2
1398    2.2
1399    4.0
1400    4.3
1401    4.0
1402    4.3
1403    3.1
1404    3.4
1405    3.4
1406    3.7
1407    3.8
1408    3.5
1409    3.9
1410    3.8
1411    3.5
1412    3.9
1413    3.8
1414    3.9
1415    3.6
1416    3.6
1417    4.2
1418    4.4
1419    4.1
1420    4.0
1421    4.1
1422    4.1
1423    4.1
1424    3.4
1425    3.6
1426    3.9
1427    3.8
1428    3.1
1429    3.4
1430    2.9
1431    3.6
1432    3.8
1433    3.6
1434    3.6
1435    3.5
1436    3.5
1437    3.8
1438    4.2
1439    4.1
1440    4.1
1441    4.0
1442    4.4
1443    4.2
1444    4.1
1445    3.4
1446    3.6
1447    3.3
1448    3.4
1449    2.6
1450    2.6
1451    2.7
1452    2.9
1453    3.8
1454    2.6
1455    3.2
1456    3.6
1457    3.6
1458    3.8
1459    3.6
1460    4.0
1461    2.6
1462    2.7
1463    2.8
1464    4.6
1465    3.6
1466    3.9
1467    3.8
1468    4.1
1469    3.3
1470    2.7
1471    2.8
1472    2.8
1473    3.2
1474    3.2
1475    3.3
1476    3.4
1477    3.4
1478    4.6
1479    3.7
1480    3.6
1481    3.6
1482    3.8
1483    3.5
1484    3.5
1485    3.6
1486    3.7
1487    3.6
1488    3.9
1489    3.9
1490    3.7
1491    3.5
1492    3.6
1493    4.2
1494    4.0
1495    4.0
1496    3.1
1497    2.8
1498    3.1
1499    2.8
1500    0.0
1501    2.8
1502    0.0
1503    2.9
1504    2.7
1505    3.4
1506    2.7
1507    3.6
1508    3.6
1509    3.8
1510    3.8
1511    4.0
1512    3.8
1513    0.0
1514    2.7
1515    3.4
1516    2.8
1517    3.6
1518    2.8
1519    3.7
1520    3.7
1521    3.4
1522    3.6
1523    4.1
1524    3.0
1525    3.0
1526    3.0
1527    3.2
1528    2.8
1529    3.3
1530    3.3
1531    3.2
1532    3.1
1533    2.8
1534    3.4
1535    3.2
1536    2.6
1537    3.2
1538    2.8
1539    2.7
1540    2.8
1541    3.1
1542    3.1
1543    3.8
1544    3.8
1545    3.6
1546    3.7
1547    3.5
1548    3.6
1549    2.3
1550    2.4
1551    4.1
1552    3.3
1553    3.5
1554    3.7
1555    4.1
1556    3.2
1557    3.0
1558    3.2
1559    2.6
1560    3.7
1561    3.5
1562    2.7
1563    3.3
1564    3.4
1565    3.4
1566    2.9
1567    3.4
1568    2.9
1569    2.6
1570    3.3
1571    3.4
1572    3.1
1573    3.7
1574    3.6
1575    3.6
1576    3.6
1577    3.5
1578    3.5
1579    3.7
1580    3.7
1581    3.8
1582    2.3
1583    2.1
1584    2.3
1585    4.0
1586    3.3
1587    3.4
1588    3.0
1589    2.9
1590    3.2
1591    3.2
1592    3.2
1593    3.2
1594    2.9
1595    3.4
1596    3.2
1597    3.1
1598    3.3
1599    3.1
1600    2.9
1601    3.1
1602    2.6
1603    3.0
1604    3.1
1605    3.0
1606    3.3
1607    3.4
1608    3.4
1609    2.7
1610    2.9
1611    3.2
1612    3.1
1613    2.8
1614    3.0
1615    2.9
1616    3.0
1617    2.5
1618    3.3
1619    3.0
1620    2.8
1621    3.5
1622    3.6
1623    3.5
1624    0.0
1625    0.0
1626    0.0
1627    0.0
1628    0.0
1629    2.2
1630    3.6
1631    2.4
1632    4.1
1633    3.2
1634    3.4
1635    3.8
1636    3.5
1637    3.9
1638    3.7
1639    3.5
1640    3.5
1641    3.1
1642    3.1
1643    2.9
1644    3.2
1645    3.2
1646    3.2
1647    2.9
1648    3.2
1649    2.9
1650    3.1
1651    2.7
1652    2.5
1653    3.0
1654    3.1
1655    3.1
1656    3.0
1657    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0

In [ ]:
# Select only numeric columns from X to train the Linear Regression model
X_numeric = X.select_dtypes(include=[np.number])

lr = LinearRegression()
lr.fit(X_numeric, Y)
y_pred_lr=lr.predict(X_numeric)
y_pred_lr

array([4.41413647, 4.55260384, 4.9016285 , ..., 5.46621272, 5.58550318,
       4.41979405])

In [ ]:
lr.score(X_numeric,Y)

0.33955881307449576

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression

# 1. Create the dataset with area, bedroom, age, and price
data_house = pd.DataFrame({
    'area': [1500, 1800, 2400, 3000, 1200, 3500],
    'bedroom': [3, 3, 4, 4, 2, 5],
    'age': [10, 15, 5, 8, 20, 2],
    'price': [400000, 450000, 580000, 650000, 320000, 780000]
})
data_house

   area  bedroom  age   price
0  1500        3   10  400000
1  1800        3   15  450000
2  2400        4    5  580000
3  3000        4    8  650000
4  1200        2   20  320000
5  3500        5    2  780000

In [ ]:
x=data_house.drop('price',axis=1)
y=data_house['price']

In [ ]:
print(x)
print(y)

   area  bedroom  age
0  1500        3   10
1  1800        3   15
2  2400        4    5
3  3000        4    8
4  1200        2   20
5  3500        5    2
0    400000
1    450000
2    580000
3    650000
4    320000
5    780000
Name: price, dtype: int64

In [ ]:
x

   area  bedroom  age
0  1500        3   10
1  1800        3   15
2  2400        4    5
3  3000        4    8
4  1200        2   20
5  3500        5    2

In [ ]:
y

0    400000
1    450000
2    580000
3    650000
4    320000
5    780000
Name: price, dtype: int64

In [ ]:
lr=LinearRegression()
lr.fit(x,y)

LinearRegression()

In [ ]:
y_pred_lr=lr.predict(x)
y_pred_lr

array([403735.02304147, 453423.96313364, 576161.29032258, 653877.88018433,
       315214.28571429, 777587.55760369])

In [ ]:
lr.score(x,y)

0.9994266314243021

In [ ]:
#to perform the regularization techniques
lasso=Lasso(alpha=1000)
lasso.fit(x,y)

Lasso(alpha=1000)

In [ ]:
y_pred_lasso=lasso.predict(x)
y_pred_lasso

array([406899.42143035, 439199.35987694, 576036.79337046, 665919.81507376,
       320421.3155335 , 771523.29471499])

In [ ]:
lasso.score(x,y)

0.9965569795559925

In [ ]:
#l2 regularization
ridge=Ridge(alpha=1000)
ridge

Ridge(alpha=1000)

In [ ]:
lr=lr.fit(x,y)
lr

LinearRegression()

In [ ]:
lr.score(x,y)

0.9994266314243021

In [ ]:
#polynomial
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)
x_poly=poly.fit_transform(x)
x_poly
poily_model=LinearRegression()
poily_model.fit(x_poly,y)
y_pred_poly=poily_model.predict(x_poly)
y_pred_poly
poily_model.score(x_poly,y)

1.0